services:
  fastapi-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-api
    restart: always
    ports:
      - "8000:8000"
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      API_KEY: ${API_KEY}
      DB_ENGINE: ${DB_ENGINE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
    networks: 
      - expenses_app_network


networks:
  expenses_app_network:
    external: true